export const characters: { [key: string]: any } = {
  "10000002": {
    nameTextMapHash: "1006042610",
    icon: "UI_AvatarIcon_Ayaka",
    sideIcon: "UI_AvatarIcon_Side_Ayaka",
    gachaIcon: "UI_Gacha_AvatarImg_Ayaka",
    constellations: [
      "UI_Talent_S_Ayaka_01",
      "UI_Talent_S_Ayaka_02",
      "UI_Talent_U_Ayaka_02",
      "UI_Talent_S_Ayaka_03",
      "UI_Talent_U_Ayaka_01",
      "UI_Talent_S_Ayaka_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_Ayaka_01",
      elementalBurst: "Skill_E_Ayaka",
    },
  },
  "10000003": {
    nameTextMapHash: "3221566250",
    icon: "UI_AvatarIcon_Qin",
    sideIcon: "UI_AvatarIcon_Side_Qin",
    gachaIcon: "UI_Gacha_AvatarImg_Qin",
    constellations: [
      "UI_Talent_S_Qin_01",
      "UI_Talent_S_Qin_02",
      "UI_Talent_U_Qin_02",
      "UI_Talent_S_Qin_03",
      "UI_Talent_U_Qin_01",
      "UI_Talent_S_Qin_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_Qin_02",
      elementalBurst: "Skill_E_Qin_01",
    },
    costumes: [
      {
        sideIconName: "UI_AvatarIcon_Side_QinCostumeSea",
        icon: "UI_AvatarIcon_QinCostumeSea",
        art: "UI_Costume_QinCostumeSea",
      },
      {
        sideIconName: "UI_AvatarIcon_Side_QinCostumeWic",
        icon: "UI_AvatarIcon_QinCostumeWic",
        art: "UI_Costume_QinCostumeWic",
      },
    ],
  },
  "10000005": {
    nameTextMapHash: "1533656818",
    icon: "UI_AvatarIcon_PlayerBoy",
    sideIcon: "UI_AvatarIcon_Side_PlayerBoy",
    gachaIcon: "UI_Gacha_AvatarImg_PlayerBoy",
    constellations: [
      "UI_Talent_S_PlayerWind_01",
      "UI_Talent_S_PlayerWind_02",
      "UI_Talent_U_PlayerWind_02",
      "UI_Talent_S_PlayerWind_03",
      "UI_Talent_U_PlayerWind_01",
      "UI_Talent_S_PlayerWind_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_PlayerWind_01",
      elementalBurst: "Skill_E_PlayerWind_01",
    },
  },
  "10000006": {
    nameTextMapHash: "3344622722",
    icon: "UI_AvatarIcon_Lisa",
    sideIcon: "UI_AvatarIcon_Side_Lisa",
    gachaIcon: "UI_Gacha_AvatarImg_Lisa",
    constellations: [
      "UI_Talent_S_Lisa_01",
      "UI_Talent_S_Lisa_02",
      "UI_Talent_U_Lisa_02",
      "UI_Talent_S_Lisa_03",
      "UI_Talent_U_Lisa_01",
      "UI_Talent_S_Lisa_04",
    ],
    skills: {
      normalAttack: "Skill_A_Catalyst_MD",
      elementalSkill: "Skill_S_Lisa_01",
      elementalBurst: "Skill_E_Lisa_01",
    },
  },
  "10000007": {
    nameTextMapHash: "3816664530",
    icon: "UI_AvatarIcon_PlayerGirl",
    sideIcon: "UI_AvatarIcon_Side_PlayerGirl",
    gachaIcon: "UI_Gacha_AvatarImg_PlayerGirl",
    constellations: [
      "UI_Talent_S_PlayerWind_01",
      "UI_Talent_S_PlayerWind_02",
      "UI_Talent_U_PlayerWind_02",
      "UI_Talent_S_PlayerWind_03",
      "UI_Talent_U_PlayerWind_01",
      "UI_Talent_S_PlayerWind_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_PlayerWind_01",
      elementalBurst: "Skill_E_PlayerWind_01",
    },
  },
  "10000014": {
    nameTextMapHash: "3775299170",
    icon: "UI_AvatarIcon_Barbara",
    sideIcon: "UI_AvatarIcon_Side_Barbara",
    gachaIcon: "UI_Gacha_AvatarImg_Barbara",
    constellations: [
      "UI_Talent_S_Barbara_01",
      "UI_Talent_S_Barbara_02",
      "UI_Talent_U_Barbara_02",
      "UI_Talent_S_Barbara_03",
      "UI_Talent_U_Barbara_01",
      "UI_Talent_S_Barbara_04",
    ],
    skills: {
      normalAttack: "Skill_A_Catalyst_MD",
      elementalSkill: "Skill_S_Barbara_01",
      elementalBurst: "Skill_E_Barbara_01",
    },
    costumes: [
      {
        sideIconName: "UI_AvatarIcon_Side_BarbaraCostumeSummertime",
        icon: "UI_AvatarIcon_BarbaraCostumeSummertime",
        art: "UI_Costume_BarbaraCostumeSummertime",
      },
    ],
  },
  "10000015": {
    nameTextMapHash: "4119663210",
    icon: "UI_AvatarIcon_Kaeya",
    sideIcon: "UI_AvatarIcon_Side_Kaeya",
    gachaIcon: "UI_Gacha_AvatarImg_Kaeya",
    constellations: [
      "UI_Talent_S_Kaeya_01",
      "UI_Talent_S_Kaeya_02",
      "UI_Talent_U_Kaeya_01",
      "UI_Talent_S_Kaeya_03",
      "UI_Talent_U_Kaeya_02",
      "UI_Talent_S_Kaeya_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_Kaeya_01",
      elementalBurst: "Skill_E_Kaeya_01",
    },
  },
  "10000016": {
    nameTextMapHash: "3608180322",
    icon: "UI_AvatarIcon_Diluc",
    sideIcon: "UI_AvatarIcon_Side_Diluc",
    gachaIcon: "UI_Gacha_AvatarImg_Diluc",
    constellations: [
      "UI_Talent_S_Diluc_01",
      "UI_Talent_S_Diluc_02",
      "UI_Talent_U_Diluc_01",
      "UI_Talent_S_Diluc_03",
      "UI_Talent_U_Diluc_02",
      "UI_Talent_S_Diluc_04",
    ],
    skills: {
      normalAttack: "Skill_A_04",
      elementalSkill: "Skill_S_Diluc_01_01",
      elementalBurst: "Skill_E_Diluc_01",
    },
    costumes: [
      {
        sideIconName: "UI_AvatarIcon_Side_DilucCostumeFlamme",
        icon: "UI_AvatarIcon_DilucCostumeFlamme",
        art: "UI_Costume_DilucCostumeFlamme",
      },
    ],
  },
  "10000020": {
    nameTextMapHash: "4160147242",
    icon: "UI_AvatarIcon_Razor",
    sideIcon: "UI_AvatarIcon_Side_Razor",
    gachaIcon: "UI_Gacha_AvatarImg_Razor",
    constellations: [
      "UI_Talent_S_Razor_01",
      "UI_Talent_S_Razor_02",
      "UI_Talent_U_Razor_02",
      "UI_Talent_S_Razor_03",
      "UI_Talent_U_Razor_01",
      "UI_Talent_S_Razor_04",
    ],
    skills: {
      normalAttack: "Skill_A_04",
      elementalSkill: "Skill_S_Razor_01",
      elementalBurst: "Skill_E_Razor_01",
    },
  },
  "10000021": {
    nameTextMapHash: "1966438658",
    icon: "UI_AvatarIcon_Ambor",
    sideIcon: "UI_AvatarIcon_Side_Ambor",
    gachaIcon: "UI_Gacha_AvatarImg_Ambor",
    constellations: [
      "UI_Talent_S_Ambor_01",
      "UI_Talent_S_Ambor_02",
      "UI_Talent_U_Ambor_02",
      "UI_Talent_S_Ambor_03",
      "UI_Talent_U_Ambor_01",
      "UI_Talent_S_Ambor_04",
    ],
    skills: {
      normalAttack: "Skill_A_02",
      elementalSkill: "Skill_S_Ambor_01",
      elementalBurst: "Skill_E_Ambor",
    },
    costumes: [
      {
        sideIconName: "UI_AvatarIcon_Side_AmborCostumeWic",
        icon: "UI_AvatarIcon_AmborCostumeWic",
        art: "UI_Costume_AmborCostumeWic",
      },
    ],
  },
  "10000022": {
    nameTextMapHash: "2466140362",
    icon: "UI_AvatarIcon_Venti",
    sideIcon: "UI_AvatarIcon_Side_Venti",
    gachaIcon: "UI_Gacha_AvatarImg_Venti",
    constellations: [
      "UI_Talent_S_Venti_01",
      "UI_Talent_S_Venti_02",
      "UI_Talent_U_Venti_02",
      "UI_Talent_S_Venti_03",
      "UI_Talent_U_Venti_01",
      "UI_Talent_S_Venti_04",
    ],
    skills: {
      normalAttack: "Skill_A_02",
      elementalSkill: "Skill_S_Venti_01",
      elementalBurst: "Skill_E_Venti_01",
    },
  },
  "10000023": {
    nameTextMapHash: "1130996346",
    icon: "UI_AvatarIcon_Xiangling",
    sideIcon: "UI_AvatarIcon_Side_Xiangling",
    gachaIcon: "UI_Gacha_AvatarImg_Xiangling",
    constellations: [
      "UI_Talent_S_Xiangling_01",
      "UI_Talent_S_Xiangling_02",
      "UI_Talent_U_Xiangling_02",
      "UI_Talent_S_Xiangling_03",
      "UI_Talent_U_Xiangling_01",
      "UI_Talent_S_Xiangling_04",
    ],
    skills: {
      normalAttack: "Skill_A_03",
      elementalSkill: "Skill_S_Xiangling_01",
      elementalBurst: "Skill_E_Xiangling_01",
    },
  },
  "10000024": {
    nameTextMapHash: "2646367730",
    icon: "UI_AvatarIcon_Beidou",
    sideIcon: "UI_AvatarIcon_Side_Beidou",
    gachaIcon: "UI_Gacha_AvatarImg_Beidou",
    constellations: [
      "UI_Talent_S_Beidou_02",
      "UI_Talent_S_Beidou_01",
      "UI_Talent_U_Beidou_01",
      "UI_Talent_S_Beidou_03",
      "UI_Talent_U_Beidou_02",
      "UI_Talent_S_Beidou_04",
    ],
    skills: {
      normalAttack: "Skill_A_04",
      elementalSkill: "Skill_S_Beidou_01",
      elementalBurst: "Skill_E_Beidou_01",
    },
  },
  "10000025": {
    nameTextMapHash: "4197635682",
    icon: "UI_AvatarIcon_Xingqiu",
    sideIcon: "UI_AvatarIcon_Side_Xingqiu",
    gachaIcon: "UI_Gacha_AvatarImg_Xingqiu",
    constellations: [
      "UI_Talent_S_Xingqiu_01",
      "UI_Talent_S_Xingqiu_02",
      "UI_Talent_U_Xingqiu_01",
      "UI_Talent_S_Xingqiu_03",
      "UI_Talent_U_Xingqiu_02",
      "UI_Talent_S_Xingqiu_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_Xingqiu_01",
      elementalBurst: "Skill_E_Xingqiu_01",
    },
  },
  "10000026": {
    nameTextMapHash: "1021947690",
    icon: "UI_AvatarIcon_Xiao",
    sideIcon: "UI_AvatarIcon_Side_Xiao",
    gachaIcon: "UI_Gacha_AvatarImg_Xiao",
    constellations: [
      "UI_Talent_S_Xiao_01",
      "UI_Talent_S_Xiao_02",
      "UI_Talent_U_Xiao_01",
      "UI_Talent_S_Xiao_03",
      "UI_Talent_U_Xiao_02",
      "UI_Talent_S_Xiao_04",
    ],
    skills: {
      normalAttack: "Skill_A_03",
      elementalSkill: "Skill_S_Xiao_01",
      elementalBurst: "Skill_E_Xiao_01",
    },
  },
  "10000027": {
    nameTextMapHash: "4127888970",
    icon: "UI_AvatarIcon_Ningguang",
    sideIcon: "UI_AvatarIcon_Side_Ningguang",
    gachaIcon: "UI_Gacha_AvatarImg_Ningguang",
    constellations: [
      "UI_Talent_S_Ningguang_01",
      "UI_Talent_S_Ningguang_05",
      "UI_Talent_U_Ningguang_02",
      "UI_Talent_S_Ningguang_03",
      "UI_Talent_U_Ningguang_01",
      "UI_Talent_S_Ningguang_04",
    ],
    skills: {
      normalAttack: "Skill_A_Catalyst_MD",
      elementalSkill: "Skill_S_Ningguang_01",
      elementalBurst: "Skill_E_Ningguang_01",
    },
    costumes: [
      {
        sideIconName: "UI_AvatarIcon_Side_NingguangCostumeFloral",
        icon: "UI_AvatarIcon_NingguangCostumeFloral",
        art: "UI_Costume_NingguangCostumeFloral",
      },
    ],
  },
  "10000029": {
    nameTextMapHash: "3339083250",
    icon: "UI_AvatarIcon_Klee",
    sideIcon: "UI_AvatarIcon_Side_Klee",
    gachaIcon: "UI_Gacha_AvatarImg_Klee",
    constellations: [
      "UI_Talent_S_Klee_01",
      "UI_Talent_S_Klee_02",
      "UI_Talent_U_Klee_01",
      "UI_Talent_S_Klee_03",
      "UI_Talent_U_Klee_02",
      "UI_Talent_S_Klee_04",
    ],
    skills: {
      normalAttack: "Skill_A_Catalyst_MD",
      elementalSkill: "Skill_S_Klee_01",
      elementalBurst: "Skill_E_Klee_01",
    },
  },
  "10000030": {
    nameTextMapHash: "3862787418",
    icon: "UI_AvatarIcon_Zhongli",
    sideIcon: "UI_AvatarIcon_Side_Zhongli",
    gachaIcon: "UI_Gacha_AvatarImg_Zhongli",
    constellations: [
      "UI_Talent_S_Zhongli_01",
      "UI_Talent_S_Zhongli_02",
      "UI_Talent_U_Zhongli_01",
      "UI_Talent_S_Zhongli_03",
      "UI_Talent_U_Zhongli_02",
      "UI_Talent_S_Zhongli_04",
    ],
    skills: {
      normalAttack: "Skill_A_03",
      elementalSkill: "Skill_S_Zhongli_01",
      elementalBurst: "Skill_E_Zhongli_01",
    },
  },
  "10000031": {
    nameTextMapHash: "3277782506",
    icon: "UI_AvatarIcon_Fischl",
    sideIcon: "UI_AvatarIcon_Side_Fischl",
    gachaIcon: "UI_Gacha_AvatarImg_Fischl",
    constellations: [
      "UI_Talent_S_Fischl_01",
      "UI_Talent_S_Fischl_02",
      "UI_Talent_U_Fischl_01",
      "UI_Talent_S_Fischl_03",
      "UI_Talent_U_Fischl_02",
      "UI_Talent_S_Fischl_04",
    ],
    skills: {
      normalAttack: "Skill_A_02",
      elementalSkill: "Skill_S_Fischl_01",
      elementalBurst: "Skill_E_Fischl_01",
    },
    costumes: [
      {
        sideIconName: "UI_AvatarIcon_Side_FischlCostumeHighness",
        icon: "UI_AvatarIcon_FischlCostumeHighness",
        art: "UI_Costume_FischlCostumeHighness",
      },
    ],
  },
  "10000032": {
    nameTextMapHash: "968893378",
    icon: "UI_AvatarIcon_Bennett",
    sideIcon: "UI_AvatarIcon_Side_Bennett",
    gachaIcon: "UI_Gacha_AvatarImg_Bennett",
    constellations: [
      "UI_Talent_S_Bennett_01",
      "UI_Talent_S_Bennett_02",
      "UI_Talent_U_Bennett_01",
      "UI_Talent_S_Bennett_03",
      "UI_Talent_U_Bennett_02",
      "UI_Talent_S_Bennett_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_Bennett_01",
      elementalBurst: "Skill_E_Bennett_01",
    },
  },
  "10000033": {
    nameTextMapHash: "3847143266",
    icon: "UI_AvatarIcon_Tartaglia",
    sideIcon: "UI_AvatarIcon_Side_Tartaglia",
    gachaIcon: "UI_Gacha_AvatarImg_Tartaglia",
    constellations: [
      "UI_Talent_S_Tartaglia_01",
      "UI_Talent_S_Tartaglia_02",
      "UI_Talent_U_Tartaglia_01",
      "UI_Talent_S_Tartaglia_05",
      "UI_Talent_U_Tartaglia_02",
      "UI_Talent_S_Tartaglia_04",
    ],
    skills: {
      normalAttack: "Skill_A_02",
      elementalSkill: "Skill_S_Tartaglia_01",
      elementalBurst: "Skill_E_Tartaglia_01",
    },
  },
  "10000034": {
    nameTextMapHash: "1921418842",
    icon: "UI_AvatarIcon_Noel",
    sideIcon: "UI_AvatarIcon_Side_Noel",
    gachaIcon: "UI_Gacha_AvatarImg_Noel",
    constellations: [
      "UI_Talent_S_Noel_01",
      "UI_Talent_S_Noel_02",
      "UI_Talent_U_Noel_01",
      "UI_Talent_S_Noel_03",
      "UI_Talent_U_Noel_02",
      "UI_Talent_S_Noel_04",
    ],
    skills: {
      normalAttack: "Skill_A_04",
      elementalSkill: "Skill_S_Noel_01",
      elementalBurst: "Skill_E_Noel_01",
    },
  },
  "10000035": {
    nameTextMapHash: "168956722",
    icon: "UI_AvatarIcon_Qiqi",
    sideIcon: "UI_AvatarIcon_Side_Qiqi",
    gachaIcon: "UI_Gacha_AvatarImg_Qiqi",
    constellations: [
      "UI_Talent_S_Qiqi_01",
      "UI_Talent_S_Qiqi_02",
      "UI_Talent_U_Qiqi_01",
      "UI_Talent_S_Qiqi_03",
      "UI_Talent_U_Qiqi_02",
      "UI_Talent_S_Qiqi_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_Qiqi_01",
      elementalBurst: "Skill_E_Qiqi_01",
    },
  },
  "10000036": {
    nameTextMapHash: "2876340530",
    icon: "UI_AvatarIcon_Chongyun",
    sideIcon: "UI_AvatarIcon_Side_Chongyun",
    gachaIcon: "UI_Gacha_AvatarImg_Chongyun",
    constellations: [
      "UI_Talent_S_Chongyun_01",
      "UI_Talent_S_Chongyun_02",
      "UI_Talent_U_Chongyun_01",
      "UI_Talent_S_Chongyun_03",
      "UI_Talent_U_Chongyun_02",
      "UI_Talent_S_Chongyun_04",
    ],
    skills: {
      normalAttack: "Skill_A_04",
      elementalSkill: "Skill_S_Chongyun_01",
      elementalBurst: "Skill_E_Chongyun_01",
    },
  },
  "10000037": {
    nameTextMapHash: "2679781122",
    icon: "UI_AvatarIcon_Ganyu",
    sideIcon: "UI_AvatarIcon_Side_Ganyu",
    gachaIcon: "UI_Gacha_AvatarImg_Ganyu",
    constellations: [
      "UI_Talent_S_Ganyu_01",
      "UI_Talent_S_Ganyu_02",
      "UI_Talent_U_Ganyu_01",
      "UI_Talent_S_Ganyu_03",
      "UI_Talent_U_Ganyu_02",
      "UI_Talent_S_Ganyu_04",
    ],
    skills: {
      normalAttack: "Skill_A_02",
      elementalSkill: "Skill_S_Ganyu_01",
      elementalBurst: "Skill_E_Ganyu_01",
    },
  },
  "10000038": {
    nameTextMapHash: "4108620722",
    icon: "UI_AvatarIcon_Albedo",
    sideIcon: "UI_AvatarIcon_Side_Albedo",
    gachaIcon: "UI_Gacha_AvatarImg_Albedo",
    constellations: [
      "UI_Talent_S_Albedo_01",
      "UI_Talent_S_Albedo_02",
      "UI_Talent_U_Albedo_01",
      "UI_Talent_S_Albedo_03",
      "UI_Talent_U_Albedo_02",
      "UI_Talent_S_Albedo_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_Albedo_01",
      elementalBurst: "Skill_E_Albedo_01",
    },
  },
  "10000039": {
    nameTextMapHash: "1468367538",
    icon: "UI_AvatarIcon_Diona",
    sideIcon: "UI_AvatarIcon_Side_Diona",
    gachaIcon: "UI_Gacha_AvatarImg_Diona",
    constellations: [
      "UI_Talent_S_Diona_01",
      "UI_Talent_S_Diona_02",
      "UI_Talent_U_Diona_01",
      "UI_Talent_S_Diona_03",
      "UI_Talent_U_Diona_02",
      "UI_Talent_S_Diona_04",
    ],
    skills: {
      normalAttack: "Skill_A_02",
      elementalSkill: "Skill_S_Diona_01",
      elementalBurst: "Skill_E_Diona_01",
    },
  },
  "10000041": {
    nameTextMapHash: "1113306282",
    icon: "UI_AvatarIcon_Mona",
    sideIcon: "UI_AvatarIcon_Side_Mona",
    gachaIcon: "UI_Gacha_AvatarImg_Mona",
    constellations: [
      "UI_Talent_S_Mona_01",
      "UI_Talent_S_Mona_02",
      "UI_Talent_U_Mona_01",
      "UI_Talent_S_Mona_03",
      "UI_Talent_U_Mona_02",
      "UI_Talent_S_Mona_04",
    ],
    skills: {
      normalAttack: "Skill_A_Catalyst_MD",
      elementalSkill: "Skill_S_Mona_01",
      elementalBurst: "Skill_E_Mona_01",
    },
    costumes: [
      {
        sideIconName: "UI_AvatarIcon_Side_MonaCostumeWic",
        icon: "UI_AvatarIcon_MonaCostumeWic",
        art: "UI_Costume_MonaCostumeWic",
      },
    ],
  },
  "10000042": {
    nameTextMapHash: "1864015138",
    icon: "UI_AvatarIcon_Keqing",
    sideIcon: "UI_AvatarIcon_Side_Keqing",
    gachaIcon: "UI_Gacha_AvatarImg_Keqing",
    constellations: [
      "UI_Talent_S_Keqing_01",
      "UI_Talent_S_Keqing_02",
      "UI_Talent_U_Keqing_01",
      "UI_Talent_S_Keqing_03",
      "UI_Talent_U_Keqing_02",
      "UI_Talent_S_Keqing_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_Keqing_01",
      elementalBurst: "Skill_E_Keqing_01",
    },
    costumes: [
      {
        sideIconName: "UI_AvatarIcon_Side_KeqingCostumeFeather",
        icon: "UI_AvatarIcon_KeqingCostumeFeather",
        art: "UI_Costume_KeqingCostumeFeather",
      },
    ],
  },
  "10000043": {
    nameTextMapHash: "1053433018",
    icon: "UI_AvatarIcon_Sucrose",
    sideIcon: "UI_AvatarIcon_Side_Sucrose",
    gachaIcon: "UI_Gacha_AvatarImg_Sucrose",
    constellations: [
      "UI_Talent_S_Sucrose_01",
      "UI_Talent_S_Sucrose_02",
      "UI_Talent_U_Sucrose_01",
      "UI_Talent_S_Sucrose_03",
      "UI_Talent_U_Sucrose_02",
      "UI_Talent_S_Sucrose_04",
    ],
    skills: {
      normalAttack: "Skill_A_Catalyst_MD",
      elementalSkill: "Skill_S_Sucrose_01",
      elementalBurst: "Skill_E_Sucrose_01",
    },
  },
  "10000044": {
    nameTextMapHash: "4273845410",
    icon: "UI_AvatarIcon_Xinyan",
    sideIcon: "UI_AvatarIcon_Side_Xinyan",
    gachaIcon: "UI_Gacha_AvatarImg_Xinyan",
    constellations: [
      "UI_Talent_S_Xinyan_01",
      "UI_Talent_S_Xinyan_02",
      "UI_Talent_U_Xinyan_01",
      "UI_Talent_S_Xinyan_03",
      "UI_Talent_U_Xinyan_02",
      "UI_Talent_S_Xinyan_04",
    ],
    skills: {
      normalAttack: "Skill_A_04",
      elementalSkill: "Skill_S_Xinyan_01",
      elementalBurst: "Skill_E_Xinyan_01",
    },
  },
  "10000045": {
    nameTextMapHash: "4260733330",
    icon: "UI_AvatarIcon_Rosaria",
    sideIcon: "UI_AvatarIcon_Side_Rosaria",
    gachaIcon: "UI_Gacha_AvatarImg_Rosaria",
    constellations: [
      "UI_Talent_S_Rosaria_01",
      "UI_Talent_S_Rosaria_02",
      "UI_Talent_U_Rosaria_01",
      "UI_Talent_S_Rosaria_03",
      "UI_Talent_U_Rosaria_02",
      "UI_Talent_S_Rosaria_04",
    ],
    skills: {
      normalAttack: "Skill_A_03",
      elementalSkill: "Skill_S_Rosaria_01",
      elementalBurst: "Skill_E_Rosaria_01",
    },
    costumes: [
      {
        sideIconName: "UI_AvatarIcon_Side_RosariaCostumeWic",
        icon: "UI_AvatarIcon_RosariaCostumeWic",
        art: "UI_Costume_RosariaCostumeWic",
      },
    ],
  },
  "10000046": {
    nameTextMapHash: "1940919994",
    icon: "UI_AvatarIcon_Hutao",
    sideIcon: "UI_AvatarIcon_Side_Hutao",
    gachaIcon: "UI_Gacha_AvatarImg_Hutao",
    constellations: [
      "UI_Talent_S_Hutao_03",
      "UI_Talent_S_Hutao_01",
      "UI_Talent_U_Hutao_01",
      "UI_Talent_S_Hutao_02",
      "UI_Talent_U_Hutao_02",
      "UI_Talent_S_Hutao_04",
    ],
    skills: {
      normalAttack: "Skill_A_03",
      elementalSkill: "Skill_S_Hutao_01",
      elementalBurst: "Skill_E_Hutao_01",
    },
  },
  "10000047": {
    nameTextMapHash: "88505754",
    icon: "UI_AvatarIcon_Kazuha",
    sideIcon: "UI_AvatarIcon_Side_Kazuha",
    gachaIcon: "UI_Gacha_AvatarImg_Kazuha",
    constellations: [
      "UI_Talent_S_Kazuha_01",
      "UI_Talent_S_Kazuha_02",
      "UI_Talent_U_Kazuha_01",
      "UI_Talent_S_Kazuha_03",
      "UI_Talent_U_Kazuha_02",
      "UI_Talent_S_Kazuha_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_Kazuha_01",
      elementalBurst: "Skill_E_Kazuha_01",
    },
  },
  "10000048": {
    nameTextMapHash: "697277554",
    icon: "UI_AvatarIcon_Feiyan",
    sideIcon: "UI_AvatarIcon_Side_Feiyan",
    gachaIcon: "UI_Gacha_AvatarImg_Feiyan",
    constellations: [
      "UI_Talent_S_Feiyan_01",
      "UI_Talent_S_Feiyan_02",
      "UI_Talent_U_Feiyan_01",
      "UI_Talent_S_Feiyan_03",
      "UI_Talent_U_Feiyan_02",
      "UI_Talent_S_Feiyan_04",
    ],
    skills: {
      normalAttack: "Skill_A_Catalyst_MD",
      elementalSkill: "Skill_S_Feiyan_01",
      elementalBurst: "Skill_E_Feiyan_01",
    },
  },
  "10000049": {
    nameTextMapHash: "2504399314",
    icon: "UI_AvatarIcon_Yoimiya",
    sideIcon: "UI_AvatarIcon_Side_Yoimiya",
    gachaIcon: "UI_Gacha_AvatarImg_Yoimiya",
    constellations: [
      "UI_Talent_S_Yoimiya_01",
      "UI_Talent_S_Yoimiya_02",
      "UI_Talent_U_Yoimiya_01",
      "UI_Talent_S_Yoimiya_03",
      "UI_Talent_U_Yoimiya_02",
      "UI_Talent_S_Yoimiya_04",
    ],
    skills: {
      normalAttack: "Skill_A_02",
      elementalSkill: "Skill_S_Yoimiya_01",
      elementalBurst: "Skill_E_Yoimiya_01",
    },
  },
  "10000050": {
    nameTextMapHash: "3555115602",
    icon: "UI_AvatarIcon_Tohma",
    sideIcon: "UI_AvatarIcon_Side_Tohma",
    gachaIcon: "UI_Gacha_AvatarImg_Tohma",
    constellations: [
      "UI_Talent_S_Tohma_01",
      "UI_Talent_S_Tohma_02",
      "UI_Talent_U_Tohma_01",
      "UI_Talent_S_Tohma_03",
      "UI_Talent_U_Tohma_02",
      "UI_Talent_S_Tohma_04",
    ],
    skills: {
      normalAttack: "Skill_A_03",
      elementalSkill: "Skill_S_Tohma_01",
      elementalBurst: "Skill_E_Tohma_01",
    },
  },
  "10000051": {
    nameTextMapHash: "3717667418",
    icon: "UI_AvatarIcon_Eula",
    sideIcon: "UI_AvatarIcon_Side_Eula",
    gachaIcon: "UI_Gacha_AvatarImg_Eula",
    constellations: [
      "UI_Talent_S_Eula_02",
      "UI_Talent_S_Eula_01",
      "UI_Talent_U_Eula_01",
      "UI_Talent_S_Eula_03",
      "UI_Talent_U_Eula_02",
      "UI_Talent_S_Eula_04",
    ],
    skills: {
      normalAttack: "Skill_A_04",
      elementalSkill: "Skill_S_Eula_01",
      elementalBurst: "Skill_E_Eula_01",
    },
  },
  "10000052": {
    nameTextMapHash: "3024507506",
    icon: "UI_AvatarIcon_Shougun",
    sideIcon: "UI_AvatarIcon_Side_Shougun",
    gachaIcon: "UI_Gacha_AvatarImg_Shougun",
    constellations: [
      "UI_Talent_S_Shougun_01",
      "UI_Talent_S_Shougun_03",
      "UI_Talent_U_Shougun_02",
      "UI_Talent_S_Shougun_02",
      "UI_Talent_U_Shougun_01",
      "UI_Talent_S_Shougun_04",
    ],
    skills: {
      normalAttack: "Skill_A_03",
      elementalSkill: "Skill_S_Shougun_01",
      elementalBurst: "Skill_E_Shougun_01",
    },
  },
  "10000053": {
    nameTextMapHash: "2388785242",
    icon: "UI_AvatarIcon_Sayu",
    sideIcon: "UI_AvatarIcon_Side_Sayu",
    gachaIcon: "UI_Gacha_AvatarImg_Sayu",
    constellations: [
      "UI_Talent_S_Sayu_01",
      "UI_Talent_S_Sayu_02",
      "UI_Talent_U_Sayu_02",
      "UI_Talent_S_Sayu_03",
      "UI_Talent_U_Sayu_01",
      "UI_Talent_S_Sayu_04",
    ],
    skills: {
      normalAttack: "Skill_A_04",
      elementalSkill: "Skill_S_Sayu_01",
      elementalBurst: "Skill_E_Sayu_01",
    },
  },
  "10000054": {
    nameTextMapHash: "3914045794",
    icon: "UI_AvatarIcon_Kokomi",
    sideIcon: "UI_AvatarIcon_Side_Kokomi",
    gachaIcon: "UI_Gacha_AvatarImg_Kokomi",
    constellations: [
      "UI_Talent_S_Kokomi_01",
      "UI_Talent_S_Kokomi_02",
      "UI_Talent_U_Kokomi_02",
      "UI_Talent_S_Kokomi_03",
      "UI_Talent_U_Kokomi_01",
      "UI_Talent_S_Kokomi_04",
    ],
    skills: {
      normalAttack: "Skill_A_Catalyst_MD",
      elementalSkill: "Skill_S_Kokomi_01",
      elementalBurst: "Skill_E_Kokomi_01",
    },
  },
  "10000055": {
    nameTextMapHash: "3400133546",
    icon: "UI_AvatarIcon_Gorou",
    sideIcon: "UI_AvatarIcon_Side_Gorou",
    gachaIcon: "UI_Gacha_AvatarImg_Gorou",
    constellations: [
      "UI_Talent_S_Gorou_01",
      "UI_Talent_S_Gorou_02",
      "UI_Talent_U_Gorou_01",
      "UI_Talent_S_Gorou_03",
      "UI_Talent_U_Gorou_02",
      "UI_Talent_S_Gorou_04",
    ],
    skills: {
      normalAttack: "Skill_A_02",
      elementalSkill: "Skill_S_Gorou_01",
      elementalBurst: "Skill_E_Gorou_01",
    },
  },
  "10000056": {
    nameTextMapHash: "1483922610",
    icon: "UI_AvatarIcon_Sara",
    sideIcon: "UI_AvatarIcon_Side_Sara",
    gachaIcon: "UI_Gacha_AvatarImg_Sara",
    constellations: [
      "UI_Talent_S_Sara_05",
      "UI_Talent_S_Sara_02",
      "UI_Talent_U_Sara_02",
      "UI_Talent_S_Sara_03",
      "UI_Talent_U_Sara_01",
      "UI_Talent_S_Sara_04",
    ],
    skills: {
      normalAttack: "Skill_A_02",
      elementalSkill: "Skill_S_Sara_01",
      elementalBurst: "Skill_E_Sara_01",
    },
  },
  "10000057": {
    nameTextMapHash: "3068316954",
    icon: "UI_AvatarIcon_Itto",
    sideIcon: "UI_AvatarIcon_Side_Itto",
    gachaIcon: "UI_Gacha_AvatarImg_Itto",
    constellations: [
      "UI_Talent_S_Itto_01",
      "UI_Talent_S_Itto_02",
      "UI_Talent_U_Itto_01",
      "UI_Talent_S_Itto_03",
      "UI_Talent_U_Itto_02",
      "UI_Talent_S_Itto_04",
    ],
    skills: {
      normalAttack: "Skill_A_04",
      elementalSkill: "Skill_S_Itto_01",
      elementalBurst: "Skill_E_Itto_01",
    },
  },
  "10000058": {
    nameTextMapHash: "2713453234",
    icon: "UI_AvatarIcon_Yae",
    sideIcon: "UI_AvatarIcon_Side_Yae",
    gachaIcon: "UI_Gacha_AvatarImg_Yae",
    constellations: [
      "UI_Talent_S_Yae_01",
      "UI_Talent_S_Yae_02",
      "UI_Talent_U_Yae_01",
      "UI_Talent_S_Yae_03",
      "UI_Talent_U_Yae_02",
      "UI_Talent_S_Yae_04",
    ],
    skills: {
      normalAttack: "Skill_A_Catalyst_MD",
      elementalSkill: "Skill_S_Yae_01",
      elementalBurst: "Skill_E_Yae_01",
    },
  },
  "10000059": {
    nameTextMapHash: "646032090",
    icon: "UI_AvatarIcon_Heizo",
    sideIcon: "UI_AvatarIcon_Side_Heizo",
    gachaIcon: "UI_Gacha_AvatarImg_Heizo",
    constellations: [
      "UI_Talent_S_Heizo_01",
      "UI_Talent_S_Heizo_02",
      "UI_Talent_U_Heizo_01",
      "UI_Talent_S_Heizo_03",
      "UI_Talent_U_Heizo_02",
      "UI_Talent_S_Heizo_04",
    ],
    skills: {
      normalAttack: "Skill_A_Catalyst_MD",
      elementalSkill: "Skill_S_Heizo_01",
      elementalBurst: "Skill_E_Heizo_01",
    },
  },
  "10000060": {
    nameTextMapHash: "2848374378",
    icon: "UI_AvatarIcon_Yelan",
    sideIcon: "UI_AvatarIcon_Side_Yelan",
    gachaIcon: "UI_Gacha_AvatarImg_Yelan",
    constellations: [
      "UI_Talent_S_Yelan_01",
      "UI_Talent_S_Yelan_02",
      "UI_Talent_U_Yelan_01",
      "UI_Talent_S_Yelan_03",
      "UI_Talent_U_Yelan_02",
      "UI_Talent_S_Yelan_04",
    ],
    skills: {
      normalAttack: "Skill_A_02",
      elementalSkill: "Skill_S_Yelan_01",
      elementalBurst: "Skill_E_Yelan_01",
    },
  },
  "10000062": {
    nameTextMapHash: "3689108098",
    icon: "UI_AvatarIcon_Aloy",
    sideIcon: "UI_AvatarIcon_Side_Aloy",
    gachaIcon: "UI_Gacha_AvatarImg_Aloy",
    constellations: [
      "UI_Talent_S_Aloy_Lock",
      "UI_Talent_S_Aloy_Lock",
      "UI_Talent_S_Aloy_Lock",
      "UI_Talent_S_Aloy_Lock",
      "UI_Talent_S_Aloy_Lock",
      "UI_Talent_S_Aloy_Lock",
    ],
    skills: {
      normalAttack: "Skill_A_02",
      elementalSkill: "Skill_S_Aloy_01",
      elementalBurst: "Skill_E_Aloy_01",
    },
  },
  "10000063": {
    nameTextMapHash: "334242634",
    icon: "UI_AvatarIcon_Shenhe",
    sideIcon: "UI_AvatarIcon_Side_Shenhe",
    gachaIcon: "UI_Gacha_AvatarImg_Shenhe",
    constellations: [
      "UI_Talent_S_Shenhe_02",
      "UI_Talent_S_Shenhe_01",
      "UI_Talent_U_Shenhe_01",
      "UI_Talent_S_Shenhe_03",
      "UI_Talent_U_Shenhe_02",
      "UI_Talent_S_Shenhe_04",
    ],
    skills: {
      normalAttack: "Skill_A_03",
      elementalSkill: "Skill_S_Shenhe_01",
      elementalBurst: "Skill_E_Shenhe_01",
    },
  },
  "10000064": {
    nameTextMapHash: "655825874",
    icon: "UI_AvatarIcon_Yunjin",
    sideIcon: "UI_AvatarIcon_Side_Yunjin",
    gachaIcon: "UI_Gacha_AvatarImg_Yunjin",
    constellations: [
      "UI_Talent_S_Yunjin_01",
      "UI_Talent_S_Yunjin_02",
      "UI_Talent_U_Yunjin_01",
      "UI_Talent_S_Yunjin_03",
      "UI_Talent_U_Yunjin_02",
      "UI_Talent_S_Yunjin_04",
    ],
    skills: {
      normalAttack: "Skill_A_03",
      elementalSkill: "Skill_S_Yunjin_01",
      elementalBurst: "Skill_E_Yunjin_01",
    },
  },
  "10000065": {
    nameTextMapHash: "1940821986",
    icon: "UI_AvatarIcon_Shinobu",
    sideIcon: "UI_AvatarIcon_Side_Shinobu",
    gachaIcon: "UI_Gacha_AvatarImg_Shinobu",
    constellations: [
      "UI_Talent_S_Shinobu_01",
      "UI_Talent_S_Shinobu_02",
      "UI_Talent_U_Shinobu_01",
      "UI_Talent_S_Shinobu_03",
      "UI_Talent_U_Shinobu_02",
      "UI_Talent_S_Shinobu_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_Shinobu_01",
      elementalBurst: "Skill_E_Shinobu_01",
    },
  },
  "10000066": {
    nameTextMapHash: "1588620330",
    icon: "UI_AvatarIcon_Ayato",
    sideIcon: "UI_AvatarIcon_Side_Ayato",
    gachaIcon: "UI_Gacha_AvatarImg_Ayato",
    constellations: [
      "UI_Talent_S_Ayato_01",
      "UI_Talent_S_Ayato_02",
      "UI_Talent_U_Ayato_02",
      "UI_Talent_S_Ayato_03",
      "UI_Talent_U_Ayato_01",
      "UI_Talent_S_Ayato_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_Ayato_01",
      elementalBurst: "Skill_E_Ayato_01",
    },
  },
  "10000067": {
    nameTextMapHash: "2948362178",
    icon: "UI_AvatarIcon_Collei",
    sideIcon: "UI_AvatarIcon_Side_Collei",
    gachaIcon: "UI_Gacha_AvatarImg_Collei",
    constellations: [
      "UI_Talent_S_Collei_01",
      "UI_Talent_S_Collei_02",
      "UI_Talent_U_Collei_02",
      "UI_Talent_S_Collei_03",
      "UI_Talent_U_Collei_01",
      "UI_Talent_S_Collei_04",
    ],
    skills: {
      normalAttack: "Skill_A_02",
      elementalSkill: "Skill_S_Collei_01",
      elementalBurst: "Skill_E_Collei_01",
    },
  },
  "10000068": {
    nameTextMapHash: "388272194",
    icon: "UI_AvatarIcon_Dori",
    sideIcon: "UI_AvatarIcon_Side_Dori",
    gachaIcon: "UI_Gacha_AvatarImg_Dori",
    constellations: [
      "UI_Talent_S_Dori_01",
      "UI_Talent_S_Dori_02",
      "UI_Talent_U_Dori_02",
      "UI_Talent_S_Dori_03",
      "UI_Talent_U_Dori_01",
      "UI_Talent_S_Dori_04",
    ],
    skills: {
      normalAttack: "Skill_A_04",
      elementalSkill: "Skill_S_Dori_01",
      elementalBurst: "Skill_E_Dori_01",
    },
  },
  "10000069": {
    nameTextMapHash: "2506955778",
    icon: "UI_AvatarIcon_Tighnari",
    sideIcon: "UI_AvatarIcon_Side_Tighnari",
    gachaIcon: "UI_Gacha_AvatarImg_Tighnari",
    constellations: [
      "UI_Talent_S_Tighnari_01",
      "UI_Talent_S_Tighnari_02",
      "UI_Talent_U_Tighnari_01",
      "UI_Talent_S_Tighnari_03",
      "UI_Talent_U_Tighnari_02",
      "UI_Talent_S_Tighnari_04",
    ],
    skills: {
      normalAttack: "Skill_A_02",
      elementalSkill: "Skill_S_Tighnari_01",
      elementalBurst: "Skill_E_Tighnari_01",
    },
  },
  "10000070": {
    nameTextMapHash: "3850149970",
    icon: "UI_AvatarIcon_Nilou",
    sideIcon: "UI_AvatarIcon_Side_Nilou",
    gachaIcon: "UI_Gacha_AvatarImg_Nilou",
    constellations: [
      "UI_Talent_S_Nilou_01",
      "UI_Talent_S_Nilou_02",
      "UI_Talent_U_Nilou_01",
      "UI_Talent_S_Nilou_03",
      "UI_Talent_U_Nilou_02",
      "UI_Talent_S_Nilou_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_Nilou_01",
      elementalBurst: "Skill_E_Nilou_01",
    },
  },
  "10000071": {
    nameTextMapHash: "1049891906",
    icon: "UI_AvatarIcon_Cyno",
    sideIcon: "UI_AvatarIcon_Side_Cyno",
    gachaIcon: "UI_Gacha_AvatarImg_Cyno",
    constellations: [
      "UI_Talent_S_Cyno_01",
      "UI_Talent_S_Cyno_02",
      "UI_Talent_U_Cyno_01",
      "UI_Talent_S_Cyno_03",
      "UI_Talent_U_Cyno_02",
      "UI_Talent_S_Cyno_04",
    ],
    skills: {
      normalAttack: "Skill_A_03",
      elementalSkill: "Skill_S_Cyno_01",
      elementalBurst: "Skill_E_Cyno_01",
    },
  },
  "10000072": {
    nameTextMapHash: "3092975658",
    icon: "UI_AvatarIcon_Candace",
    sideIcon: "UI_AvatarIcon_Side_Candace",
    gachaIcon: "UI_Gacha_AvatarImg_Candace",
    constellations: [
      "UI_Talent_S_Candace_01",
      "UI_Talent_S_Candace_02",
      "UI_Talent_U_Candace_01",
      "UI_Talent_S_Candace_03",
      "UI_Talent_U_Candace_02",
      "UI_Talent_S_Candace_04",
    ],
    skills: {
      normalAttack: "Skill_A_03",
      elementalSkill: "Skill_S_Candace_01",
      elementalBurst: "Skill_E_Candace_01",
    },
  },
  "10000073": {
    nameTextMapHash: "712501082",
    icon: "UI_AvatarIcon_Nahida",
    sideIcon: "UI_AvatarIcon_Side_Nahida",
    gachaIcon: "UI_Gacha_AvatarImg_Nahida",
    constellations: [
      "UI_Talent_S_Nahida_01",
      "UI_Talent_S_Nahida_02",
      "UI_Talent_U_Nahida_01",
      "UI_Talent_S_Nahida_03",
      "UI_Talent_U_Nahida_02",
      "UI_Talent_S_Nahida_04",
    ],
    skills: {
      normalAttack: "Skill_A_Catalyst_MD",
      elementalSkill: "Skill_S_Nahida_01",
      elementalBurst: "Skill_E_Nahida_01",
    },
  },
  "10000074": {
    nameTextMapHash: "2889777514",
    icon: "UI_AvatarIcon_Layla",
    sideIcon: "UI_AvatarIcon_Side_Layla",
    gachaIcon: "UI_Gacha_AvatarImg_Layla",
    constellations: [
      "UI_Talent_S_Layla_01",
      "UI_Talent_S_Layla_02",
      "UI_Talent_U_Layla_01",
      "UI_Talent_S_Layla_03",
      "UI_Talent_U_Layla_02",
      "UI_Talent_S_Layla_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_Layla_01",
      elementalBurst: "Skill_E_Layla_01",
    },
  },
  "10000075": {
    nameTextMapHash: "3230559562",
    icon: "UI_AvatarIcon_Wanderer",
    sideIcon: "UI_AvatarIcon_Side_Wanderer",
    gachaIcon: "UI_Gacha_AvatarImg_Wanderer",
    constellations: [
      "UI_Talent_S_Wanderer_01",
      "UI_Talent_S_Wanderer_02",
      "UI_Talent_U_Wanderer_02",
      "UI_Talent_S_Wanderer_03",
      "UI_Talent_U_Wanderer_01",
      "UI_Talent_S_Wanderer_04",
    ],
    skills: {
      normalAttack: "Skill_A_Catalyst_MD",
      elementalSkill: "Skill_S_Wanderer_01",
      elementalBurst: "Skill_E_Wanderer_01",
    },
  },
  "10000076": {
    nameTextMapHash: "2387711994",
    icon: "UI_AvatarIcon_Faruzan",
    sideIcon: "UI_AvatarIcon_Side_Faruzan",
    gachaIcon: "UI_Gacha_AvatarImg_Faruzan",
    constellations: [
      "UI_Talent_S_Faruzan_01",
      "UI_Talent_S_Faruzan_02",
      "UI_Talent_U_Faruzan_01",
      "UI_Talent_S_Faruzan_03",
      "UI_Talent_U_Faruzan_02",
      "UI_Talent_S_Faruzan_04",
    ],
    skills: {
      normalAttack: "Skill_A_02",
      elementalSkill: "Skill_S_Faruzan_01",
      elementalBurst: "Skill_E_Faruzan_01",
    },
  },
  "10000005-501": {
    nameTextMapHash: "3816664530",
    icon: "UI_AvatarIcon_PlayerBoy",
    sideIcon: "UI_AvatarIcon_Side_PlayerBoy",
    gachaIcon: "UI_Gacha_AvatarImg_PlayerBoy",
    constellations: ["None", "None", "None", "None", "None", "None"],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "None",
      elementalBurst: "None",
    },
  },
  "10000005-504": {
    nameTextMapHash: "1533656818",
    icon: "UI_AvatarIcon_PlayerBoy",
    sideIcon: "UI_AvatarIcon_Side_PlayerBoy",
    gachaIcon: "UI_Gacha_AvatarImg_PlayerBoy",
    constellations: [
      "UI_Talent_S_PlayerWind_01",
      "UI_Talent_S_PlayerWind_02",
      "UI_Talent_U_PlayerWind_02",
      "UI_Talent_S_PlayerWind_03",
      "UI_Talent_U_PlayerWind_01",
      "UI_Talent_S_PlayerWind_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_PlayerWind_01",
      elementalBurst: "Skill_E_PlayerWind_01",
    },
  },
  "10000005-506": {
    nameTextMapHash: "1533656818",
    icon: "UI_AvatarIcon_PlayerBoy",
    sideIcon: "UI_AvatarIcon_Side_PlayerBoy",
    gachaIcon: "UI_Gacha_AvatarImg_PlayerBoy",
    constellations: [
      "UI_Talent_S_PlayerRock_01",
      "UI_Talent_S_PlayerRock_02",
      "UI_Talent_U_PlayerRock_02",
      "UI_Talent_S_PlayerRock_03",
      "UI_Talent_U_PlayerRock_01",
      "UI_Talent_S_PlayerRock_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_PlayerRock_01",
      elementalBurst: "Skill_E_PlayerRock_01",
    },
  },
  "10000005-507": {
    nameTextMapHash: "1533656818",
    icon: "UI_AvatarIcon_PlayerBoy",
    sideIcon: "UI_AvatarIcon_Side_PlayerBoy",
    gachaIcon: "UI_Gacha_AvatarImg_PlayerBoy",
    constellations: [
      "UI_Talent_S_PlayerElectric_01",
      "UI_Talent_S_PlayerElectric_02",
      "UI_Talent_U_PlayerElectric_01",
      "UI_Talent_S_PlayerElectric_03",
      "UI_Talent_U_PlayerElectric_02",
      "UI_Talent_S_PlayerElectric_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_PlayerElectric_01",
      elementalBurst: "Skill_E_PlayerElectric_01",
    },
  },
  "10000005-508": {
    nameTextMapHash: "1533656818",
    icon: "UI_AvatarIcon_PlayerBoy",
    sideIcon: "UI_AvatarIcon_Side_PlayerBoy",
    gachaIcon: "UI_Gacha_AvatarImg_PlayerBoy",
    constellations: [
      "UI_Talent_S_PlayerGrass_01",
      "UI_Talent_S_PlayerGrass_02",
      "UI_Talent_S_PlayerGrass_03",
      "UI_Talent_S_PlayerGrass_04",
      "UI_Talent_S_PlayerGrass_05",
      "UI_Talent_S_PlayerGrass_06",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_E_PlayerGrass_01",
      elementalBurst: "Skill_S_PlayerGrass_01",
    },
  },
  "10000007-701": {
    nameTextMapHash: "3816664530",
    icon: "UI_AvatarIcon_PlayerGirl",
    sideIcon: "UI_AvatarIcon_Side_PlayerGirl",
    gachaIcon: "UI_Gacha_AvatarImg_PlayerGirl",
    constellations: ["None", "None", "None", "None", "None", "None"],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "None",
      elementalBurst: "None",
    },
  },
  "10000007-704": {
    nameTextMapHash: "3816664530",
    icon: "UI_AvatarIcon_PlayerGirl",
    sideIcon: "UI_AvatarIcon_Side_PlayerGirl",
    gachaIcon: "UI_Gacha_AvatarImg_PlayerGirl",
    constellations: [
      "UI_Talent_S_PlayerWind_01",
      "UI_Talent_S_PlayerWind_02",
      "UI_Talent_U_PlayerWind_02",
      "UI_Talent_S_PlayerWind_03",
      "UI_Talent_U_PlayerWind_01",
      "UI_Talent_S_PlayerWind_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_PlayerWind_01",
      elementalBurst: "Skill_E_PlayerWind_01",
    },
  },
  "10000007-706": {
    nameTextMapHash: "3816664530",
    icon: "UI_AvatarIcon_PlayerGirl",
    sideIcon: "UI_AvatarIcon_Side_PlayerGirl",
    gachaIcon: "UI_Gacha_AvatarImg_PlayerGirl",
    constellations: [
      "UI_Talent_S_PlayerRock_01",
      "UI_Talent_S_PlayerRock_02",
      "UI_Talent_U_PlayerRock_02",
      "UI_Talent_S_PlayerRock_03",
      "UI_Talent_U_PlayerRock_01",
      "UI_Talent_S_PlayerRock_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_PlayerRock_01",
      elementalBurst: "Skill_E_PlayerRock_01",
    },
  },
  "10000007-707": {
    nameTextMapHash: "3816664530",
    icon: "UI_AvatarIcon_PlayerGirl",
    sideIcon: "UI_AvatarIcon_Side_PlayerGirl",
    gachaIcon: "UI_Gacha_AvatarImg_PlayerGirl",
    constellations: [
      "UI_Talent_S_PlayerElectric_01",
      "UI_Talent_S_PlayerElectric_02",
      "UI_Talent_U_PlayerElectric_01",
      "UI_Talent_S_PlayerElectric_03",
      "UI_Talent_U_PlayerElectric_02",
      "UI_Talent_S_PlayerElectric_04",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_S_PlayerElectric_01",
      elementalBurst: "Skill_E_PlayerElectric_01",
    },
  },
  "10000007-708": {
    nameTextMapHash: "3816664530",
    icon: "UI_AvatarIcon_PlayerGirl",
    sideIcon: "UI_AvatarIcon_Side_PlayerGirl",
    gachaIcon: "UI_Gacha_AvatarImg_PlayerGirl",
    constellations: [
      "UI_Talent_S_PlayerGrass_01",
      "UI_Talent_S_PlayerGrass_02",
      "UI_Talent_S_PlayerGrass_03",
      "UI_Talent_S_PlayerGrass_04",
      "UI_Talent_S_PlayerGrass_05",
      "UI_Talent_S_PlayerGrass_06",
    ],
    skills: {
      normalAttack: "Skill_A_01",
      elementalSkill: "Skill_E_PlayerGrass_01",
      elementalBurst: "Skill_S_PlayerGrass_01",
    },
  },
};